name: Deploy to AWS Lambda

on:
  push:
    branches:
      - "master"

env:
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  TRANSCRIPTION_S3_BUCKET: ${{secrets.TRANSCRIPTION_S3_BUCKET}}
  TEMP_STORAGE_FOLDER: ${{secrets.TEMP_STORAGE_FOLDER}}
  WIT_TOKEN: ${{secrets.WIT_TOKEN}}
  GC_BUCKET: ${{secrets.GC_BUCKET}}
  GC_CREDENTIALS: ${{secrets.GC_CREDENTIALS}}

jobs:
  deploy:
    name: "Serverless Deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Deploy
        run: npx serverless@2.62.0 deploy
